### ISSUE TITLE
Sorting by publish date and etc not working

### ISSUE THREAD

**Issue by hardcorp74** [dragomano/grav-plugin-yandex-turbo#11]
Sorting by publish date not working

Direction is working fine

**Comment by hardcorp74** [comment]
Set as on picture
![image](https://user-images.githubusercontent.com/5231223/95957915-cbbc0400-0e19-11eb-8b4b-0dbcbbeca632.png)

But last page with (<pubDate>Thu, 27 Aug 20 21:23:00 +0300</pubDate>) in middle of rss...
Before last update it was first.

**Comment by dragomano** [comment]
Is there a "publish_date" field in the page frontmatter?
Sorting is working, but the RSS shows the date create/update only.

**Comment by hardcorp74** [comment]
`<pubDate>Thu, 20 Feb 20 21:44:00 +0300</pubDate>` as example

in web as example, in MD for example
`date: '22:00 07/23/2020'`
![image](https://user-images.githubusercontent.com/5231223/95982789-fddd5e00-0e39-11eb-9da5-bac7abc27905.png)

Before last update sorting was fine in rss

**Comment by dragomano** [comment]
I mean the **publish** date, not the create/update date.
![Publish date](https://user-images.githubusercontent.com/229402/95985943-b0afbb00-0e3e-11eb-91e3-e3133ecc696b.png)

**Comment by hardcorp74** [comment]
Thank you, I understand what you mean )

**Comment by HarDX** [comment]
About priority
/
/blog
/etc

can display
first from / - by sorting
after
second from /blog - by sorting
