### ISSUE TITLE
[Enhancement] Custom path for turbo page index

### ISSUE THREAD

**Issue by hardcorp74** [dragomano/grav-plugin-yandex-turbo#3]
Need set custom path for turbo page. Not main page, for example custom path set to: /blog for rss indexing.

**Comment by dragomano** [comment]
Can you test [this PR](https://github.com/dragomano/grav-plugin-yandex-turbo/pull/4)?
I hope it makes what you ask.

**Comment by hardcorp74** [comment]
Yes, but by default after update now in settings / and if not save, all info from /blog. After save / path - all is ok - from main page.
After save /blog all is ok from /blog

Route chages working too.

Everything is fine at first test.
