### ISSUE TITLE
[Enhancement] Yandex restriction

### ISSUE THREAD

**Issue by hardcorp74** [dragomano/grav-plugin-yandex-turbo#5]
I donn't see any restriction about this info in source
![image](https://user-images.githubusercontent.com/5231223/95573931-a0b26880-0a45-11eb-816e-7ceffd4af6ed.png)

Maybe need restrict item/pictures and some other info.

**Comment by hardcorp74** [comment]
Maybee need return only last 1000 - item, and check amount of pictures...

**Comment by dragomano** [comment]
Currently, this plugin takes the 1000 last pages only (sorted by date), with one image for every item section.
But I can add the limit for the title, h1, author tags.

**Comment by hardcorp74** [comment]
Found ) slice(0, 1000); 
Cool, restrict - title, h1, author tags - may be useful too
