### ISSUE TITLE
Images in rss content is monochrome

### ISSUE THREAD

**Issue by hardcorp74** [dragomano/grav-plugin-yandex-turbo#7]
Images in rss content is monochrome

![image](https://user-images.githubusercontent.com/5231223/95580204-60a4b300-0a50-11eb-843b-4433895fbc76.png)

but in real
![image](https://user-images.githubusercontent.com/5231223/95580246-774b0a00-0a50-11eb-9edc-51a0bcae1693.png)

**Comment by dragomano** [comment]
I made it specially, as a feature :)

**Comment by hardcorp74** [comment]
May be checkbox in settings? )
