### ISSUE TITLE
Need priority in content to display field

### ISSUE THREAD

**Issue by hardcorp74** [dragomano/grav-plugin-yandex-turbo#8]
May be need priority for content to display.
First is upper
![image](https://user-images.githubusercontent.com/5231223/95580451-ca24c180-0a50-11eb-9833-8e7a28cbabd8.png)

Now it sort all pages from / and /blog by date in sum.

**Comment by HarDX** [comment]
About priority
/
/blog
/etc

can display
first from / - by sorting
after
second from /blog - by sorting
